### ISSUE TITLE
Mocking in a different package breaks unexported methods

### ISSUE THREAD

**Issue by adam-hanna** [uber-go/mock#199] opened 2024-08-15 23:23 UTC
*Requested feature* 
Say you have the following project structure:
```
main.go
foo/
  interface.go
```

And inside `/foo/interface.go` you have:
```
// foo/interface.go
package foo

type IFoo interface {
  Bar() int
  baz()
}
```

And you try to mock it into your main (or any package other than `foo`):
`$ mockgen -source=foo/interface.go -destination=mock.go -package=main`

And then you try to use it:
```go
// main.go
package main

import (
	"github.com/adam-hanna/mock-test/foo"
)

func main() {
	mockedFoo := MockIFoo{}
	doBar(&mockedFoo)
}

func doBar(f foo.IFoo) {
	f.Bar()
}
```

You will get the error: `cannot use &mockedFoo (value of type *MockIFoo) as foo.IFoo value in argument to doBar: *MockIFoo does not implement foo.IFoo (unexported method baz)compilerInvalidIfaceAssign`

Demo, [here](https://github.com/adam-hanna/mock-test).

If you were to mock into the `foo` package, everything is fine, but this isn't always possible.

*Why the feature is needed* 
This is needed if you are trying to mock a 3rd party library, and cannot modify their source code to add a mock. This happens to me all of the time when I'm writing tests and need to mock a 3rd party dependency.

*(Optional) Proposed solution*
The fix is quite simple. The created struct just needs to imbed the mocked interface. In my example:
```go
// MockIFoo is a mock of IFoo interface.
type MockIFoo struct {
        foo.IFoo
	ctrl     *gomock.Controller
	recorder *MockIFooMockRecorder
}
```

I don't believe doing this will break any existing code.

We may also need to add a flag for the dependency location `foo`. For example, if `foo` wasn't local, but was at github.com/adam-hanna/foo we would need to add that to the imports.

**Comment by JacobOaks** [comment] 2024-08-27 18:17
Thanks for the issue, but I think this is a duplicate of #64 so I'll close it. Please let me know if I'm mistaken.

**Closed by JacobOaks** 2024-08-27 18:17 UTC
